### ISSUE TITLE
popup.html에 크롬익스텐션 option창으로 가는 링크 걸어주세요~~

### ISSUE THREAD

**Issue by taeguk** [juice500ml/auto-lecture-evaluation#1]
[요런거](http://stackoverflow.com/questions/14584781/how-do-you-link-to-the-options-page-in-a-chrome-extension) 참고하셔서 해주시면 될거 같아요~~

**Comment by taeguk** [comment]
해주실꺼죠오오??

**Comment by juice500ml** [comment]
ee70337310900aa17cf42a94d078b0d1adf08870 커밋에 추가했습니당~

**Comment by taeguk** [comment]
개쩜!
